---
title: Active Members Assigned to Staff
output:
    html_document:
        css: "../styles/styles.css"
params:
  date: !r Sys.Date()
---
```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
source("setup.R")
```
```{r goals}
goals <- get.goals()[,c("contact_id", "name", "flo_goal_creation_date", "flo_goal_end_date")] %>%
  filter(is.na(flo_goal_end_date))
```
```{r attendance}
attendance <- get.attendance(days=90)[,c("contact_2_id","da_date_of_attendance")] %>%
  mutate(da_date_of_attendance = as_date(da_date_of_attendance)) %>%
  filter(as_date(da_date_of_attendance) >= (today() - days(90)))
```
```{r supports}
support.rel <- get.table("flo_supports_contacts_c") %>%
  select("flo_supports_contactsflo_supports_ida", "flo_supports_contactscontacts_idb")

supports <- get.supports()[,c("id", "name", "flo_support_date")] %>%
  mutate(flo_support_date = as_date(flo_support_date)) %>%
  mutate(SupportID = id) %>%
  filter(flo_support_date >= (today() - days(90))) %>%
  inner_join(support.rel, by=c("id"="flo_supports_contactsflo_supports_ida")) %>%
  ungroup()

# nrow(supports)
# ft <- goc.table(head(supports, n=100))
# ft

```
```{r progress-notes}
pn <- get.progress.notes()[,c("contact_id", "flo_date_of_note")] %>%
  mutate(flo_date_of_note = as_date(flo_date_of_note)) %>%
  filter(flo_date_of_note >= (today() - days(90)))
```
```{r assigned-staff}

members <- get.members(active.only=T) %>%
  select(id, contact_id_c, goc_contact_id, first_name, last_name) %>%

  # Add the staff name
  
  left_join(get.contacts()[,c("id","first_name")],contacts, by=c("goc_contact_id"="id")) %>%
  rename(staff_name = first_name.y, first_name = first_name.x) %>%

  # Add Open Goals

  left_join(goals, by = c("id"="contact_id")) %>%
  group_by(id, contact_id_c, first_name, last_name, staff_name) %>%
  summarize(OpenGoals = n_distinct(name, na.rm=T), RecentGoal = max(as_date(flo_goal_creation_date), na.rm=T))  %>%
  ungroup() %>%
  mutate(RecentGoal = as_date(ifelse(RecentGoal == -Inf, NA, RecentGoal))) %>%

  # Add Attendance

  left_join(attendance, by = c("contact_id_c"="contact_2_id")) %>%
  group_by(id, first_name, last_name, staff_name, OpenGoals, RecentGoal) %>%
  summarize(Visits = n_distinct(da_date_of_attendance, na.rm = T), RecentAttend = max(da_date_of_attendance, na.rm=T)) %>%
  ungroup() %>%

  # Add Supports

  left_join(supports, by = c("id" = "flo_supports_contactscontacts_idb")) %>%
  group_by(id, first_name, last_name, staff_name, OpenGoals, RecentGoal, Visits, RecentAttend) %>%
  summarise(Supports = n_distinct(SupportID, na.rm=T), RecentSupport = max(flo_support_date, na.rm=T)) %>%
  mutate(RecentSupport = as_date(ifelse(RecentSupport == -Inf, NA, RecentSupport))) %>%
  ungroup() %>%

  # Add Progress Supports

  left_join(pn, by = c("id"="contact_id")) %>%
  group_by(id, first_name, last_name, staff_name, OpenGoals, RecentGoal, Visits, RecentAttend, Supports, RecentSupport) %>%
  summarize(Notes = n_distinct(flo_date_of_note, na.rm = T), RecentNote = max(flo_date_of_note, na.rm=T)) %>%
  mutate(RecentNote = as_date(ifelse(RecentNote == -Inf, NA, RecentNote))) %>%
  ungroup() %>%

  # Cosmetics

  mutate(`Member\nName` = paste0(last_name, ", ", first_name)) %>%
  select(`Staff\nName` = staff_name, `Member\nName`,
         `Visits\nin\nlast\n90 Days` = Visits, `Most\nRecent\nVisit` = RecentAttend,
         `Supports\nin\nlast\n90 Days` = Supports, `Most\nRecent\nSupport` = RecentSupport,
         `Open\nGoals` = OpenGoals, `Most\nRecent\nGoal` = RecentGoal,
         `Progress\nNotes in\nlast 90 Days` = Notes, `Most\nRecent\nProgress\nNote` = RecentNote,
         ) %>%
  arrange(`Staff\nName`, `Member\nName`)

ft <- goc.table(members, paste0(nrow(members)," Active Members ",nrow(members[!is.na(members$`Staff\nName`),])," Assigned to Staff"))
ft
```
