---
title: Attendance Checklist for `r params$date`
output:
  html_document:
      css: "../styles/styles.css"
params:
  date: !r Sys.Date()
---
```{r setup,echo=FALSE,message=FALSE}
source("setup.R")
```
```{r attendance}
    contacts <- get.contacts()
    
    ndays <- as.integer(lubridate::as_date(Sys.Date()) - lubridate::as_date(params$date)) + 1
    
    tab <- get.attendance(days = ndays) %>%
        dplyr::filter(da_date_of_attendance == params$date) %>%
        dplyr::left_join(contacts, by = c("contact_2_id" = "id")) %>%
        dplyr::mutate(Name = paste(last_name, first_name, sep = ", ")) %>%
        dplyr::mutate(da_time_in =lubridate::as_datetime(ifelse(is.na(da_time_in),  NA, 
                                              lubridate::as_datetime(paste0(da_date_of_attendance, " ", da_time_in))))) %>%
        dplyr::mutate(da_time_out=lubridate::as_datetime(ifelse(is.na(da_time_out), NA, 
                                              lubridate::as_datetime(paste0(da_date_of_attendance, " ", da_time_out))))) %>%
        dplyr::mutate(`Time In` = format(da_time_in, "%I:%M %p")) %>%
        dplyr::mutate(`Time Out` = format(da_time_out, "%I:%M %p")) %>%
        dplyr::mutate(Hours = ifelse(is.na(da_time_out) | is.na(da_time_in) ," ",
                              format(round(as.numeric(difftime(as.POSIXct(da_time_out), 
                                                               as.POSIXct(da_time_in), units = "hours")), 2), nsmall = 2))) %>%
        dplyr::select(Name, `Time In`, `Time Out`, Hours) %>%
        dplyr::full_join(data.frame(Name = get.staff.names()), by="Name") %>%
        dplyr::arrange(Name)


ft <- goc.table(tab, paste("Checklist for", params$date))
ft
```
