---
title: "Load Member Birthdates"
output:
  html_document:
    css: "../../styles/styles.css"
---
```{r setup,echo=F,message=F,warning=F}
source(../setup.R)
```
```{r flourish}

# Get birthdates from Applistic data

birthdates <- read_csv("../../data/applistic-final/people.csv", col_types = list(Race3="c",ProviderTitle="c",ProviderSuffix="c",
                                                             Referral="c",Race8="c",Race9="c",Race12="c",Race13="c",
                                                             Race14="c", StaffIDNumber="c")) %>%
  mutate(Member=Member=="Member") %>% mutate(Member = Member & !is.na(Member)) %>%
  filter(Member) %>%
  mutate(DateOfBirth = mdy(DateOfBirth)) %>%
  mutate(DateOfBirth = ifelse(DateOfBirth > Sys.Date(), DateOfBirth-years(100), DateOfBirth)) %>%
  mutate(DateOfBirth = as_date(DateOfBirth)) %>%
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
  filter(!is.na(DateOfBirth)) %>%
  select(PersonID, FirstName, LastName, DateOfBirth, date_modified, modified_user_id)

nrow(birthdates)

ft <- goc.table(birthdates,paste("Adding Birthdates",today()))
ft
```
``` {r do-update}

# Make a database connection to Flourish

con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

# Allow Tables to be loaded from R

dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

dbSendQuery(con, 'DROP TABLE temp_contacts_update;')
dbWriteTable(con, value = birthdates, name = 'temp_contacts_update', append = F, row.names = F)

dbSendQuery(con, 'UPDATE contacts
                     INNER JOIN temp_contacts_update ON
                         contacts.flo_external_id1_c = temp_contacts_update.PersonID
                     SET contacts.date_modified = temp_contacts_update.date_modified,
                         contacts.modified_user_id = temp_contacts_update.modified_user_id,
                         contacts.birthdate = temp_contacts_update.DateOfBirth;')

dbSendQuery(con, 'DROP TABLE temp_contacts_update;')
dbDisconnect(con)

```