---
title: "Load Outreach from Applistic"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output:
  html_document: default
  word_document: 
    reference_docx: word-styles.docx
    keep_md: yes
  pdf_document: default
---

```{r setup,echo=F,message=F,warning=F}
knitr::opts_chunk$set(echo=FALSE, message=FALSE,warning=FALSE,fig.width=14)
load("~/Documents/GOC/.RData")
library(knitr)
library(rmarkdown)
library(tidyverse)
library(kableExtra)
library(lubridate)
library(stringr)
library(RMySQL)
library(flextable)
library(uuid)
previous_month <- rollback(today()-months(1),roll_to_first =TRUE) %--% rollback(today())
set_flextable_defaults(font.size = 10, theme_fun = theme_zebra, padding = 6, background.color = "#EFEFEF")
```
# Extract, Transform and Load.  From Applistic to Flourish.  Intended for one-time use.

```{r extract_applistic_outreach}

applistic.outreach <- read_csv("../../data/applistic-final/support_events.csv") %>%

    # outreach is outreach, not support

    mutate(OutreachType=SupportType) %>%

    mutate(SupportType=ifelse(SupportType=="Other Outreach","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="U.S. Mail","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="Visit - Home","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="Visit - Respite","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="Face to Face Outreach","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="Email","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="Telephone","Outreach",SupportType)) %>%
    mutate(SupportType=ifelse(SupportType=="SMS Text","Outreach",SupportType)) %>%

    filter(SupportType == "Outreach") %>%

    # Now we can recode outreach

    mutate(OutreachType=ifelse(OutreachType=="Other Outreach","Unknown",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="U.S. Mail","Letter",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="Visit - Home","Visit",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="Visit - Respite","Visit",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="Face to Face Outreach","Visit",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="Email","Email",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="Telephone","Phone",OutreachType)) %>%
    mutate(OutreachType=ifelse(OutreachType=="SMS Text","Text",OutreachType)) %>%

    # Reshape to names, datatypes, and columns of interest

    rename(StaffID=ProviderID,DateModified=LastUpdate) %>%
    mutate(DateRecCreated=mdy(DateRecCreated),Date=dmy(Date)) %>%
    mutate(StaffID=as.character(StaffID)) %>%
    select(SupportID,StaffID,OutreachType,Notes,Date,DateModified,DateRecCreated)

ft <- goc.table(tail(applistic.outreach,n=40),"From Applistic, recoded")
ft

tab <- applistic.outreach %>%
    group_by(OutreachType) %>%
    tally()
ft <- goc.table(tab,"Outreach Types")
ft
```

```{r join-memberID-from-applistic}

applistic.supported <- read_csv("../../data/applistic-final/supported_individuals.csv") %>%
    mutate(MemberID=as.character(RecipientID)) %>%
    select(SupportID,MemberID)

applistic.outreach <- applistic.outreach %>%
    left_join(applistic.supported, by="SupportID")

```

```{r join-staff-to-outreach}

con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

contacts <- dbGetQuery(con, "SELECT * FROM sa_contacts_2") %>%
    rename(person1_c=id) %>%
    select(first_name,last_name,person1_c,contact2_applistic_number)

x <- dbDisconnect(con)


# Renumber goes here

staff <-data.frame(StaffName=c("Brett","Maggie","Kyanna","Nakeshia",
                               "Cristina","Sandy","Brett","Maggie","Rose Ann",
                               "Robert","Kaitlyn","Mia","Kaitlyn","Paul","Deidra","Cristina",
                               "Kalya","Ouida","Roscoe","Jeff","Debbie","Brian","Jill","Fey","Chris",
                                "Luis","Kerry","Joseph","Robert","Barry"),
                  OldID=c("1469","1540","1633","1715","1729","1733","1822","1874","1964","1968",
                          "2026","2072","2074","2100","2076","1655","1997","1698","1425","664",
                          "1269","674","1326","1126","1154","1329","1408","312","625","649"),
                  NewID=c("3835","4038","1633","1715","3796","1733","3835","4038","1964","4039",
                          "4651","4553","4651","2100","4641","3796","3212","3907","3410","4336",
                          "4200","4025","3185","3998","4206","3603","3508","3837","3958","4130"))

contacts <- contacts %>%
    left_join(staff,by=c("contact2_applistic_number"="NewID")) %>%
    mutate(contact2_applistic_number = ifelse(!is.na(contact2_applistic_number),
                                              OldID,contact2_applistic_number)) %>%
    filter(!is.na(contact2_applistic_number))

outreach <- applistic.outreach %>%
    left_join(contacts,by=c("StaffID"="contact2_applistic_number"))

ft <- goc.table(tail(outreach,n=100), "With contact ID")
ft
```

### Join Member IDs
```{r join-member-ids}

con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

members <- dbGetQuery(con, "SELECT * FROM contacts") %>%
    rename(contact_id=id) %>%
    select(contact_id,flo_external_id1_c)

x <- dbDisconnect(con)


outreach <- outreach %>%
    left_join(members,by=c("MemberID"="flo_external_id1_c"))

ft <-goc.table(tail(outreach,n=100))
ft

```

```{r transform_outreach}

transformed.outreach <- outreach %>%

    mutate(id = UUIDgenerate(n=n())) %>%
    mutate(name = paste0("OR-",seq(1,n()))) %>%
    mutate(date_entered = Sys.time()) %>%
    mutate(date_modified = Sys.time()) %>%
    mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>% # UUID for Mike Conlon
    mutate(created_by = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
    mutate(description = "") %>%
    mutate(deleted = 0) %>%
    mutate(assigned_user_id = "") %>%

    rename(ro_date_of_reach_out=Date) %>%
    rename(ro_notes_from_reach_out=Notes) %>%
    mutate(ro_outcome_of_ro = "") %>%
    rename(ro_type_of_reachout=OutreachType) %>%
    mutate(ro_autoincrement=seq(1,n())) %>%

  # Final column select

    select(id, name, date_entered, date_modified, modified_user_id, created_by, description,
           deleted, assigned_user_id,
           ro_date_of_reach_out, ro_notes_from_reach_out, ro_outcome_of_ro, ro_type_of_reachout,
           person1_c, contact_id, ro_autoincrement)

ft <- goc.table(tail(transformed.outreach,n=100),"Ready to load")
ft

write_csv(transformed.outreach,file="../../output/transformed-outreach.csv")
```

# Connect to Flourish and write the supports data to Flourish
```{r load_supports}

# Make a database connection to Flourish
con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

# Allow Tables to be loaded from R
dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Load supports to Flourish replacing whatever is there. value is R, name is remote table

dbGetQuery(con,"DELETE FROM sa_flourish_reach_out;")
dbWriteTable(con, value = transformed.outreach, name = 'sa_flourish_reach_out', append = T, row.names = F)

dbDisconnect(con)
```