---
title: "Load Member Housing"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Get Members

members <- get.members(include.deleted = T) %>%
  select(id, flo_external_id1_c)


# Highest grade completed
# Degree(s)
# Education comments

# Get applistic info

housing <- read_csv("../../data/applistic-final/housing_history.csv") %>%
  mutate(PersonID = as.character(PersonID)) %>%
  arrange(desc(DateRecCreated)) %>%
  group_by(PersonID) %>%
  filter(row_number() == 1) %>%
  select(PersonID, HousingStatus, HousingNotes)

tab <- housing %>%
  group_by(HousingStatus) %>%
  tally()

ft <- goc.table(tab)
ft

nrow(housing)
ft <- goc.table(housing)
ft

housing <- housing %>%
    
  # Housing Status
    
  mutate(status = "") %>%
  mutate(status = ifelse(HousingStatus == 'Group Home', 'group', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Half-Way House', 'group', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Homeless', 'unshel', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Independent Living', 'ind', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Lives with Family/Friends', 'family', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Not Available or Unknown', 'unknown', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Own House', 'ind', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Rented Apartment', 'roommates', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Rented Room', 'roommates', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Shelter', 'shelter', status)) %>%
  mutate(status = ifelse(HousingStatus == 'Supported Housing (Assisted)', 'trans', status)) %>%

  inner_join(members, by=c("PersonID"="flo_external_id1_c")) %>%
  rename(flo_housing_status_c = status, flo_housing_comments = HousingNotes) %>%
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
  select(id, flo_housing_status_c, flo_housing_comments, date_modified, modified_user_id)

nrow(housing)
ft <- goc.table(housing)
ft
```

```{r do-update}
# Make a database connection to Flourish
# 
con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

# Display a column length

# rs <- dbSendQuery(con,"SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'gainesvillecrm' AND TABLE_NAME = 'contacts' AND COLUMN_NAME = 'flo_housing_status_c';")
# dbFetch(rs)

# Allow Tables to be loaded from R
dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbWriteTable(con, value = housing, name = 'temp_members_update', append = F, row.names = F)

dbSendQuery(con, 'UPDATE contacts
                  INNER JOIN temp_members_update ON
                         contacts.id = temp_members_update.id
                     SET contacts.date_modified = temp_members_update.date_modified,
                         contacts.modified_user_id = temp_members_update.modified_user_id,

                         contacts.flo_housing_status_c   = temp_members_update.flo_housing_status_c,
                         contacts.flo_housing_comments = temp_members_update.flo_housing_comments
                 ;')

dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbDisconnect(con)
```
