---
title: "Load Member Diagnoses"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Get Member Race from Applistic

members <- get.members(include.deleted = T) %>%
  select(id,flo_external_id1_c)

diagnoses <- read_csv("../../data/applistic-final/diagnoses.csv") %>%
  mutate(PersonID = as.character(PersonID)) %>%
  select(PersonID, Diagnosis) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Schizo-Effective Disorder","^schizoaffective_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Bi-Polar","^bipolar_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Schizophrenia","^schizophrenia^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Panic Disorders","^panic_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Other","", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Major Depression","^major_depressive_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Post Traumatic Stress","^post_traumatic_stress_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Mood Disorders","^mood_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Borderline Personality","^borderline_personality^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Depression Disorder","^depressive_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Personality Disorders","^personality_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Schizoaffective","^schizoaffective_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Substance Use Disorder","^substance_use_disorder^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "ADHD","^adhd^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Autism Spectrum","^autism_spectrum^", Diagnosis)) %>%
  mutate(Diagnosis = ifelse(Diagnosis == "Anxiety Disorder","^anxiety_disorder^", Diagnosis)) %>%
  filter(Diagnosis != "") %>%
  group_by(PersonID,Diagnosis) %>%
  tally() %>%
  spread(Diagnosis,n)

diagnoses[is.na(diagnoses)] <-0

diagnoses <- diagnoses %>%
  mutate(diag = "") %>%
  mutate(diag = ifelse(`^schizoaffective_disorder^` >0, paste0("^schizoaffective_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^bipolar_disorder^` > 0, paste0("^bipolar_disorder^,",diag),diag)) %>%
  mutate(diag = ifelse(`^schizophrenia^` >0, paste0("^schizophrenia^,",diag), diag)) %>%
  mutate(diag = ifelse(`^panic_disorder^` >0, paste0("^panic_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(diag == "Other","", diag)) %>%
  mutate(diag = ifelse(`^major_depressive_disorder^` >0, paste0("^major_depressive_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^post_traumatic_stress_disorder^` >0, paste0("^post_traumatic_stress_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^mood_disorder^` >0, paste0("^mood_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^borderline_personality^` >0, paste0("^borderline_personality^,",diag), diag)) %>%
  mutate(diag = ifelse(`^depressive_disorder^` >0, paste0("^depressive_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^personality_disorder^` >0, paste0("^personality_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^schizoaffective_disorder^` >0, paste0("^schizoaffective_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^substance_use_disorder^` >0, paste0("^substance_use_disorder^,",diag), diag)) %>%
  mutate(diag = ifelse(`^adhd^` >0, paste0("^adhd^,",diag), diag)) %>%
  mutate(diag = ifelse(`^autism_spectrum^` >0, paste0("^autism_spectrum^,",diag), diag)) %>%
  mutate(diag = ifelse(`^anxiety_disorder^` >0, paste0("^anxiety_disorder^,",diag), diag)) %>%
  mutate(flo_diagnoses_mult = str_sub(diag, end = -2)) %>%
  select(PersonID, flo_diagnoses_mult) %>%
  
      
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be")

diagnoses <- diagnoses %>%
  inner_join(members, by=c("PersonID"="flo_external_id1_c"))
  
nrow(diagnoses)

ft <- goc.table(diagnoses)
ft
```

```{r do-update}
# Make a database connection to Flourish

con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

# Allow Tables to be loaded from R

dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbWriteTable(con, value = diagnoses, name = 'temp_members_update', append = F, row.names = F)

dbSendQuery(con, 'UPDATE contacts
                     INNER JOIN temp_members_update ON
                         contacts.id = temp_members_update.id
                     SET contacts.date_modified = temp_members_update.date_modified,
                         contacts.modified_user_id = temp_members_update.modified_user_id,

                         contacts.flo_diagnoses_mult = temp_members_update.flo_diagnoses_mult;')

dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbDisconnect(con)
```
