---
title: "Load Member Diagnosis Note"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Getfrom Applistic data

members <- get.members(include.deleted = T)
diagnosis.note <- read_csv("../../data/applistic-final/diagnoses.csv", col_types = list(
  Race3 = "c", ProviderTitle = "c", ProviderSuffix = "c",
  Referral = "c", Race8 = "c", Race9 = "c", Race12 = "c", Race13 = "c",
  Race14 = "c", StaffIDNumber = "c"
)) %>%
  filter(DiagnosisNotes != "" & !is.na(DiagnosisNotes)) %>%
  mutate(PersonID = as.character(PersonID)) %>%
  mutate(DiagnosisDate = dmy(DiagnosisDate)) %>%
  mutate(DiagnosisNotes = ifelse(startsWith(DiagnosisNotes,"Notes:"),substring(DiagnosisNotes,7),DiagnosisNotes)) %>%
  group_by(PersonID) %>% 
  arrange(desc(DiagnosisDate)) %>%
  filter(row_number() == 1)

diagnosis.note <- members %>%
  inner_join(diagnosis.note, by = c("flo_external_id1_c" = "PersonID")) %>%
  mutate(flo_diagnosis_comments = DiagnosisNotes) %>%
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
  select(id, flo_diagnosis_comments, date_modified, modified_user_id)

nrow(diagnosis.note)

ft <- goc.table(diagnosis.note, paste("Diagnosis Comment", today()))
ft
```

```{r do-update}
# Make a database connection to Flourish

con <- dbConnect(RMySQL::MySQL(),
                       dbname = "gainesvillecrm",
                       host = "3.136.184.221",
                       port = 3306,
                       user = "mikeconlon",
                       password = "c8g8*uKkm4s4NM")

# Allow Tables to be loaded from R

dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

# dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbWriteTable(con, value = diagnosis.note, name = 'temp_members_update', append = F, row.names = F)

dbSendQuery(con, 'UPDATE contacts
                     INNER JOIN temp_members_update ON
                         contacts.id = temp_members_update.id
                     SET contacts.date_modified = temp_members_update.date_modified,
                         contacts.modified_user_id = temp_members_update.modified_user_id,

                         contacts.flo_diagnosis_comments = temp_members_update.flo_diagnosis_comments;')

dbSendQuery(con, 'DROP TABLE temp_members_update;')
dbDisconnect(con)
```
