---
title: "Load Member Income"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Get Members

members <- get.members(include.deleted = T) %>%
  select(id, flo_external_id1_c)


# SSI
# SSDI
# Food Stamps
# Annual Income

# Get applistic info

income <- read_csv("../../data/applistic-final/member_income.csv") %>%
  mutate(PersonID = as.character(PersonID)) %>%
  mutate(Amount = as.numeric(gsub("[$,]", "", Amount))) %>%
  mutate(SSI_count = ifelse(Source == "SSI", 1, 0)) %>%
  mutate(SSDI_count = ifelse(Source == "SSDI", 1, 0)) %>%
  mutate(FoodStamps_count = ifelse(Source == "Food Stamps", 1, 0)) %>%
  group_by(PersonID) %>%
  summarise(
    Income = sum(Amount),
    SSDI = max(SSDI_count),
    SSI = max(SSI_count),
    FoodStamps = max(FoodStamps_count)
  )

# nrow(income)
# 
# ft <- goc.table(income)
# ft

income <- members %>%
  inner_join(income, by = c("flo_external_id1_c" = "PersonID")) %>%
  mutate(flo_ssi = ifelse(SSI == 1, "yes", "unknown")) %>%
  mutate(flo_ssdi = ifelse(SSDI == 1, "yes", "unknown")) %>%
  mutate(flo_food_stamps = ifelse(FoodStamps == 1, "yes", "unknown")) %>%
  
  # Monthly income brackets
  
  mutate(flo_annual_income = "") %>%
  mutate(flo_annual_income = ifelse(is.na(Income) | Income == 0, "unknown", flo_annual_income)) %>%
  mutate(flo_annual_income = ifelse(Income > 0 & Income <= 1050, "le1050", flo_annual_income)) %>%
  mutate(flo_annual_income = ifelse(Income > 1050 & Income <= 1500, "fpl", flo_annual_income)) %>%
  mutate(flo_annual_income = ifelse(Income > 1500, "gt1500", flo_annual_income)) %>%
  
  # Required columns
    
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
    
  select(id,flo_ssi, flo_ssdi, flo_food_stamps, 
           flo_annual_income, date_modified, modified_user_id)


nrow(income)

ft <- goc.table(income)
ft
```

```{r do-update}
# # Make a database connection to Flourish
# 
# con <- dbConnect(RMySQL::MySQL(),
#                        dbname = "gainesvillecrm",
#                        host = "3.136.184.221",
#                        port = 3306,
#                        user = "mikeconlon",
#                        password = "c8g8*uKkm4s4NM")
# 
# # Allow Tables to be loaded from R
# 
# dbSendQuery(con, "SET GLOBAL local_infile = true;")
# 
# # Create temporary table
# 
# # dbSendQuery(con, 'DROP TABLE temp_members_update;')
# dbWriteTable(con, value = income, name = 'temp_members_update', append = F, row.names = F)
# 
# dbSendQuery(con, 'UPDATE contacts
#                      INNER JOIN temp_members_update ON
#                          contacts.id = temp_members_update.id
#                      SET contacts.date_modified = temp_members_update.date_modified,
#                          contacts.modified_user_id = temp_members_update.modified_user_id,
# 
#                         contacts.flo_ssi               = temp_members_update.flo_ssi,
#                         contacts.flo_ssdi              = temp_members_update.flo_ssdi,
#                         contacts.flo_food_stamps       = temp_members_update.flo_food_stamps,
#                         contacts.flo_annual_income     = temp_members_update.flo_annual_income
#                  ;')
# 
# dbSendQuery(con, 'DROP TABLE temp_members_update;')
# dbDisconnect(con)
```
