---
title: "Load Member Transport"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Get Transport Info from Applistic data

members <- get.members(include.deleted = T) %>%
    select(id, flo_external_id1_c)

ft <- goc.table(members)
ft

transport <- read_csv("../../data/applistic-final/transportation_history.csv", col_types = list(
  Race3 = "c", ProviderTitle = "c", ProviderSuffix = "c",
  Referral = "c", Race8 = "c", Race9 = "c", Race12 = "c", Race13 = "c",
  Race14 = "c", StaffIDNumber = "c"
)) %>%
  mutate(PersonID = as.character(PersonID)) %>%
  mutate(LastUpdate = mdy(DateRecCreated)) %>%
  mutate(flo_transportation_mode_c = "") %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Bike", "Bike", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Club Van", "GOC_van", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Drive", "Drive", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Driven by Family", "Driven_by_family_or_friend", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Driven by Residential Program", "Driven_by_housing", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Fellow Member", "Driven_by_family_or_friend", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Public Transit", "Public_transportation", flo_transportation_mode_c)) %>%
  mutate(flo_transportation_mode_c = ifelse(TransportationMode == "Walk", "Walk", flo_transportation_mode_c)) %>%
  select(PersonID, flo_transportation_mode_c)

ft <- goc.table(transport)
ft

transport <- members %>%
  inner_join(transport, by = c("flo_external_id1_c"="PersonID")) %>%
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be")

nrow(transport)

ft <- goc.table(transport, paste("Transport", today()))
ft
```

```{r do-update}
# Make a database connection to Flourish

con <- dbConnect(RMySQL::MySQL(),
  dbname = "gainesvillecrm",
  host = "3.136.184.221",
  port = 3306,
  user = "mikeconlon",
  password = "c8g8*uKkm4s4NM"
)

# Allow Tables to be loaded from R

dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

dbSendQuery(con, "DROP TABLE temp_members_update;")
dbWriteTable(con, value = transport, name = "temp_members_update", append = F, row.names = F)

dbSendQuery(con, "UPDATE contacts
                     INNER JOIN temp_members_update ON
                         contacts.id = temp_members_update.id
                     SET contacts.date_modified = temp_members_update.date_modified,
                         contacts.modified_user_id = temp_members_update.modified_user_id,

                         contacts.flo_transportation_mode_c = temp_members_update.flo_transportation_mode_c;")

dbSendQuery(con, "DROP TABLE temp_members_update;")
dbDisconnect(con)
```
