---
title: "Load Member Admin"
output:
  html_document:
    css: "../../styles/styles.css"
---

```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```

```{r flourish}
# Get Members

members <- get.members(include.deleted = T) %>%
  select(id, flo_external_id1_c)


# Referral type -- new field -- see below
# Referral Source -- enter by hand
# Referred By -- enter by hand
# Membership Date

# Get applistic info

admin <- read_csv("../../data/applistic-final/people.csv", col_types = list(
  Race3 = "c", ProviderTitle = "c", ProviderSuffix = "c",
  Referral = "c", Race8 = "c", Race9 = "c", Race12 = "c", Race13 = "c",
  Race14 = "c", StaffIDNumber = "c"
)) %>%
  mutate(PersonID = as.character(PersonID)) %>%
  mutate(Member = Member == "Member") %>%
  mutate(Member = Member & !is.na(Member)) %>%
  filter(Member) %>%
  select(PersonID, FirstName, LastName, ReferralSource, ReferralBy, MembershipDate) %>%
  mutate(flo_application_date = dmy(MembershipDate)) %>%
  inner_join(members,by=c("PersonID"="flo_external_id1_c")) %>%
  mutate(date_modified = now()) %>%
  mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
  select(-PersonID) %>%
  arrange(ReferralSource) %>%
  mutate(referral_type = "") %>%
  mutate(referral_type = ifelse(ReferralSource == "Community Hospital","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "F.A.C.T.","agency",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Family member / relative","family",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Mental Health Care Provider","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Meridian Behavioral Health Center","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "None of the Above","friend",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "North Florida Regional","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Other Court Order","agency",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Other Social Service","agency",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Physician / Doctor","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Residential Program","agency",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Self-Referral","self",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Shands/ Vista","mh_provider",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Substance Abuse Provider","agency",referral_type)) %>%
  mutate(referral_type = ifelse(ReferralSource == "Veterans Administration (VA)","mh_provider",referral_type))
  

nrow(admin)
ft <- goc.table(admin)
ft
```

```{r do-update}
# Make a database connection to Flourish

con <- dbConnect(RMySQL::MySQL(),
  dbname = "gainesvillecrm",
  host = "3.136.184.221",
  port = 3306,
  user = "mikeconlon",
  password = "c8g8*uKkm4s4NM"
)

# Display a column length

# rs <- dbSendQuery(con,"SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'gainesvillecrm' AND TABLE_NAME = 'contacts' AND COLUMN_NAME = 'flo_housing_status_c';")
# dbFetch(rs)

# Allow Tables to be loaded from R
dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

# dbSendQuery(con, "DROP TABLE temp_members_update;")
dbWriteTable(con, value = admin, name = "temp_members_update", append = F, row.names = F)

dbSendQuery(con, "UPDATE contacts
                  INNER JOIN temp_members_update ON
                         contacts.id = temp_members_update.id
                     SET contacts.date_modified = temp_members_update.date_modified,
                         contacts.modified_user_id = temp_members_update.modified_user_id,

                         contacts.referral_type   = temp_members_update.referral_type,
                         contacts.flo_application_date   = temp_members_update.flo_application_date
                 ;")

dbSendQuery(con, "DROP TABLE temp_members_update;")
dbDisconnect(con)
```
