---
title: "Clean Contact Phone"
output:
  html_document:
    css: "../../styles/styles.css"
---
```{r setup,echo=F,message=F,warning=F}
source("../setup.R")
```
Update the existing phone numbers, standardizing on the format xxx-xxx-xxxx
```{r flourish}

phones <- get.contacts(include.deleted=T) %>%
    mutate(PhoneDigits = nchar(gsub("[^0-9]+", "", c2_primary_phone))) %>%
    mutate(OldPhone = c2_primary_phone) %>%
    mutate(NewPhone = gsub("[^0-9]+", "", c2_primary_phone)) %>%
    mutate(NewPhone = paste0(substring(NewPhone,1,3),"-",
                             substring(NewPhone,4,6),"-",substring(NewPhone,7,10))) %>%
    mutate(better_phone = ifelse(PhoneDigits == 10, NewPhone, OldPhone)) %>%
    mutate(date_modified = now()) %>%
    mutate(modified_user_id = "4cde6014-5735-b6a8-2975-63e1844134be") %>%
    mutate(better_phone = ifelse(OldPhone == "NA", "", better_phone)) %>%
    filter(OldPhone != "" & OldPhone != "-" & 
               OldPhone != "N/A" & OldPhone != better_phone) %>%
    select(id,date_modified, modified_user_id,OldPhone,better_phone)

ft <- goc.table(phones,paste(nrow(phones)," Phone Number Cleaning",today()))
ft
```
``` {r do-update}

# Make a database connection to Flourish

con <- flourish.connection()

# Allow Tables to be loaded from R

dbSendQuery(con, "SET GLOBAL local_infile = true;")

# Create temporary table

dbWriteTable(con, value = phones, name = 'temp_sa_contacts_2_update', append = F, row.names = F)

dbSendQuery(con, 'UPDATE sa_contacts_2
                     INNER JOIN temp_sa_contacts_2_update ON
                         sa_contacts_2.id = temp_sa_contacts_2_update.id
                     SET sa_contacts_2.date_modified = temp_sa_contacts_2_update.date_modified,
                         sa_contacts_2.modified_user_id = temp_sa_contacts_2_update.modified_user_id,
                         sa_contacts_2.c2_primary_phone = temp_sa_contacts_2_update.better_phone;')

dbSendQuery(con, 'DROP TABLE temp_sa_contacts_2_update;')
dbDisconnect(con)

```