---
title: Current Employment
output:
    html_document:
        css: "../styles/styles.css"
params:
  date: !r Sys.Date()
---
```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
source("setup.R")
```

```{r current-employment}
emp <- get.employment()

emp <- emp %>%
  mutate(flo_emp_date_end = as_date(flo_emp_date_end)) %>%
  filter(is.na(flo_emp_date_end) | flo_emp_date_end == "") %>%
  filter(flo_emp_job_type == "TE" | flo_emp_job_type == "SE" | flo_emp_job_type == "IE") %>%
  mutate(`GOC Support` = ifelse(flo_emp_job_type == "TE" , "Transitional", ifelse( flo_emp_job_type == "SE", "Supported",  "Independent"))) %>%
  
  left_join(get.members()[,c("id","first_name","last_name")], by=c("contact_id"="id")) %>%
  mutate(Member = paste0(last_name, ", ", first_name)) %>%
  
  left_join(get.contacts()[,c("id","contact2_full_name")], by=c("employer_id"="id")) %>%
  rename(Employer = contact2_full_name) %>%
  
  select(`GOC Support`, Member, flo_emp_job_title, Employer, flo_emp_date_start, flo_emp_approximate_hourly_pay, flo_emp_approximate_hours_wk) %>%
  arrange(desc(`GOC Support`), Member) %>%
  
  rename(`Job Title` = flo_emp_job_title, `Start Date` = flo_emp_date_start, 
         `Hourly Pay`=flo_emp_approximate_hourly_pay, `Hours/Week` = flo_emp_approximate_hours_wk)

ft <- goc.table(emp, paste0(nrow(emp), " Members employed")) %>%
  colformat_num(j="Hourly Pay",big.mark=",", prefix="$")
ft


```
