---
title: GOC Last Attendance in `r format(params$date,"%B, %Y")`
output:
  html_document:
      css: "../styles/styles.css"
params:
  date: !r Sys.Date()
---

```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
source("setup.R")
```
This report lists each member who attended in the month, along with the date of most recent attendance.
```{r get-data}

start_date <- floor_date(params$date, 'month')
end_date <- ceiling_date(params$date, 'month') - days(1)

ndays <- as.integer(as_date(Sys.Date())-as_date(start_date)) +1

contacts <- get.contacts() %>%
  filter(grepl("Member", c2_groups)) %>%
  mutate(Name = paste(last_name, first_name, sep = ", ")) %>%
  select(Name, id)

attendance <- get.attendance(days = ndays)

member.attendance <- attendance %>%
  inner_join(contacts, by = c("contact_2_id" = "id"))


```

```{r last-attendance}
tab <- member.attendance %>%
  filter(as_date(da_date_of_attendance) %within% (start_date %--% end_date)) %>%
  arrange(Name, desc(da_date_of_attendance)) %>%
  group_by(Name) %>%
  summarise(`Last Visit` = max(da_date_of_attendance)) %>%
  select(Name, `Last Visit`)

ft <- goc.table(tab, paste0("Last Attendance in ", format(params$date, "%B, %Y")))
ft
```
