---
title: "Progress Notes By Staff"
output:
  html_document:
        css: "../styles/styles.css"
params:
  date: !r Sys.Date()
---

```{r setup,echo=F,message=F,warning=F}
source("setup.R")
```
```{r progress-notes}

pn <- get.progress.notes() %>%
    mutate(flo_date_of_note = as_date(flo_date_of_note)) %>%
    mutate(date_modified = as_date(date_modified)) %>%
    mutate(PNDate = as_date(ifelse ( date_modified > flo_date_of_note & date_modified != ymd("2023-02-21"), date_modified, flo_date_of_note))) %>%
    select(contact_id, contact_2_id, PNDate, date_modified, flo_date_of_note)

# ft <- goc.table(pn,"Notes")
# ft

contacts <- get.contacts() %>%
    filter(grepl("Staff", c2_groups)) %>%
    mutate(Name = paste0(last_name, ", ", first_name))

# ft <- goc.table(contacts,"Staff")
# ft

```
# Week
```{r week}
start_date <- floor_date(as_date(params$date), "week")
end_date <- min(today(), ceiling_date(as_date(params$date), "week") -1)

tab <- pn %>%
    inner_join(contacts, by=c("contact_2_id" = "id")) %>%
    filter(PNDate %within% (start_date %--% end_date)) %>%
    group_by(Name) %>%
    tally() %>%
    spread(Name,n) %>%
    mutate(across(where(is.numeric), ~ ifelse(is.na(.),0,.) ))

if (ncol(tab) > 0) {
  ft <- goc.table(tab,paste0("Progress Notes By Staff from ", start_date, " to ", end_date))
  ft
}
```
# Month
```{r month}
start_date <- floor_date(as_date(params$date), "month")
end_date <- min(today(), ceiling_date(as_date(params$date), "month") -1)

tab <- pn %>%
    inner_join(contacts, by=c("contact_2_id" = "id")) %>%
    filter(PNDate %within% (start_date %--% end_date)) %>%
    group_by(Name) %>%
    tally() %>%
    spread(Name,n) %>%
    mutate(across(where(is.numeric), ~ ifelse(is.na(.),0,.) ))

if (ncol(tab) > 0) {
  ft <- goc.table(tab,paste0("Progress Notes By Staff from ", start_date, " to ", end_date))
  ft
}
```
# Year
```{r year}
start_date <- floor_date(as_date(params$date), "year")
end_date <- min(today(), ceiling_date(as_date(params$date), "year") -1)

tab <- pn %>%
    inner_join(contacts, by=c("contact_2_id" = "id")) %>%
    filter(PNDate %within% (start_date %--% end_date)) %>%
    group_by(Name) %>%
    tally() %>%
    spread(Name,n) %>%
    mutate(across(where(is.numeric), ~ ifelse(is.na(.),0,.) ))

if (ncol(tab) > 0) {
  ft <- goc.table(tab,paste0("Progress Notes By Staff from ", start_date, " to ", end_date))
  ft
}
```
# All
```{r all}
tab <- pn %>%
    inner_join(contacts, by=c("contact_2_id" = "id")) %>%
    group_by(Name) %>%
    tally() %>%
    spread(Name,n) %>%
    mutate(across(where(is.numeric), ~ ifelse(is.na(.),0,.) ))

if (ncol(tab) > 0) {
  ft <- goc.table(tab,paste0("Progress Notes By Staff from ", start_date, " to ", end_date))
  ft
}
```
