---
title: GOC Visitor Sign-In Sheet for `r Sys.Date()+7`
output:
  html_document:
      css: "../styles/styles.css"
---

```{r setup,echo=FALSE,message=FALSE}
source("setup.R")
```
```{r attendance}
tab <- data.frame(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "") %>%
  add_row(Name = ".", Signature = "", In = "", Out = "", In.2 = "", Out.2 = "", In.3 = "", Out.3 = "")

ft <- flextable(tab) %>%
  autofit() %>%
  colformat_num(big.mark = "") %>%
  align(part = "header", align = "center") %>%
  width(j = 1, 3) %>%
  width(j = seq(3, 8), width = 0.8) %>%
  width(j = 2, width = 2.5) %>%
  set_header_labels(In.2 = "In", Out.2 = "Out", In.3 = "In", Out.3 = "Out") %>%
  set_caption(as_paragraph(as_chunk(paste("Visitor sign-in sheet for", today() + 1), props = fp_text_default(italic = T))))
ft
```
